services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_password
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookingapp-network

volumes:
  postgres_data:

networks:
  bookingapp-network:
    driver: bridge
